### ISSUE TITLE
Some errors occur while installation and fails to run with 'error while loading shared libraries' since janet 1.32.0

### ISSUE THREAD

**Issue by meinside** [Jakski/asdf-janet#2]
**Describe the bug**

Since janet 1.32.0, I see errors while installation like this:

```
Installing libjanet.so.1.33.0 to /home/ubuntu/.asdf/installs/janet/1.33.0/lib
Installing libjanet.a to /home/ubuntu/.asdf/installs/janet/1.33.0/lib
Installing janet to /home/ubuntu/.asdf/installs/janet/1.33.0/bin
Installing janet_1.33.0.h to /home/ubuntu/.asdf/installs/janet/1.33.0/include/janet
Installing /home/ubuntu/.asdf/downloads/janet/1.33.0/janet.1 to /home/ubuntu/.asdf/installs/janet/1.33.0/share/man/man1
Installing /home/ubuntu/.asdf/downloads/janet/1.33.0/build/meson-private/janet.pc to /home/ubuntu/.asdf/installs/janet/1.33.0/lib/pkgconfig
Installing /home/ubuntu/.asdf/downloads/janet/1.33.0/tools/.keep to /home/ubuntu/.asdf/installs/janet/1.33.0/lib/janet
Installing symlink pointing to libjanet.so.1.33.0 to /home/ubuntu/.asdf/installs/janet/1.33.0/lib/libjanet.so.1.33
Installing symlink pointing to libjanet.so.1.33 to /home/ubuntu/.asdf/installs/janet/1.33.0/lib/libjanet.so
Installing symlink pointing to janet/janet_1.33.0.h to /home/ubuntu/.asdf/installs/janet/1.33.0/include/janet.h
Installing symlink pointing to janet_1.33.0.h to /home/ubuntu/.asdf/installs/janet/1.33.0/include/janet/janet.h
~/.asdf/downloads/janet/1.33.0/jpm ~/.asdf/downloads/janet/1.33.0 ~
/home/ubuntu/.asdf/installs/janet/1.33.0/bin/janet: error while loading shared libraries: libjanet.so.1.33: cannot open shared object file: No such file or directory
~/.asdf/downloads/janet/1.33.0 ~
~
janet 1.33.0 installation was successful!
```

and after the installation, it fails to run like:

```
$ janet
/home/ubuntu/.asdf/installs/janet/1.33.0/bin/janet: error while loading shared libraries: libjanet.so.1.33: cannot open shared object file: No such file or directory

$
```

**Steps to reproduce**

Try installing and running janet version 1.32.0+ with asdf-janet plugin.

**Expected behavior**

It should be installed and run without any problem.

**Additional context**

It seems to be related to [this issue](https://github.com/janet-lang/janet/issues/1356).

With `LD_LIBRARY_PATH` configured (eg. `export LD_LIBRARY_PATH=$HOME/.asdf/installs/janet/1.33.0/lib`), it can be successfully installed and run.

If it is an issue with shared library, it could be remedied with `-Dshared=false` in the meson build script, but I'm not sure it would be the right solution.

**Comment by Jakski** [comment]
Thank you for initial research. The way Meson handles shared libraries is correct. After `ninja install` step it's up to user to configure dynamic libraries loader on target system. It wasn't an issue before, because Janet interpreter wasn't using any self-produced libraries. Fortunately `asdf` allows to specify `exec-env` hook to inject custom environment variables. `LD_LIBRARY_PATH` should be now correctly set on each call.

On side note: my last commit contains way more changes than just adding `LD_LIBRARY_PATH`. I refactored a few things as well, but `main` branch should work for you now.

**Comment by meinside** [comment]
Thanks for the fix!

Works great on linux, but I see these errors on macOS:

```
$ janet
/Users/meinside/.asdf/plugins/janet/bin/exec-env: line 5: [: -v: unary operator expected
/Users/meinside/.asdf/lib/commands/command-exec.bash: line 23: shim_args[@]: unbound variable
```

The version of bash bundled in latest macOS seems quite outdated :-(

```
$ uname -a
Darwin meinside.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

$ bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.

$
```

**Comment by meinside** [comment]
FYI, it's working ok with bash freshly installed with brew (version 5.2.21(1)).

**Comment by Jakski** [comment]
I've used older syntax in `exec-env` for compatibility. It should now work even with older Bash versions on MacOS.

**Comment by meinside** [comment]
Ahhh sorry for beating a dead horse here, but there was a remaining '-v' in the install script(`bin/install`).

```
$ asdf install janet
/Users/meinside/.asdf/plugins/janet/bin/install: line 13: [: -v: unary operator expected
```

And I still see this error:

```
$ janet
/Users/meinside/.asdf/lib/commands/command-exec.bash: line 23: shim_args[@]: unbound variable
```

Is this also related to the old bash version?

**Comment by Jakski** [comment]
Yes. Good catch - I've patched it as well. Strangely it wasn't caught by Github Actions earlier. Maybe they're providing newer MacOS for continuous integration.
